### ISSUE TITLE
Create a common signing function

### ISSUE THREAD

**Issue by bartekn** [lenondupe/stellar-ledger-api#3]
Currently `stellar-ledger-api` provides two functions for signing transactions: `signTx_async` and `signTxHash_async`. This is problematic because `signTx_async` supports only a set of operations (and this can change in next releases: ex. support for more operations) so developers need to keep track of what kind of transactions and operations are supported by the current version of this API.

I propose to change `signTx_async` function to call `signTxHash_async` internally when it's not able to correctly process and sign a transaction provided. I think this shouldn't have any security implications because it's not breaking existing API and users still need to accept transactions on a Ledger device.

**Comment by lenondupe** [comment]
That's a great idea. API users shouldn't have to worry about that.

**Comment by lenondupe** [comment]
I pushed some changes. Could you check they agree with your suggestion?

**Comment by bartekn** [comment]
Yes, it looks good.
