### ISSUE TITLE
Getting crashes trying to connect.  Building electron app.

### ISSUE THREAD

**Issue by sgehrman** [lenondupe/stellar-ledger-api#6]

**Comment by sgehrman** [comment]
looks like I was using an old build, will try again...

**Comment by sgehrman** [comment]
Nope, it just crashes.

**Comment by sgehrman** [comment]
Nevermind, seems that Electron doesn't support u2f so it's hopeless. I assumed it was just chrome.

**Comment by lenondupe** [comment]
Hey, I never used electron but I think it should work. u2f is only one of two communication protocols supported, the other is node-hid which should work with native bindings on nodejs. The api selects either one based on whether the window object exists. Maybe you have a top level object called window and the wrong one gets selected. To get the correct comm object try var comm = require('ledgerco').comm_node; Also make sure browser support is disabled on the device app.

**Comment by sgehrman** [comment]
Tried a few more things, but couldn't get it working. Try my project https://github.com/StellarKit/stellar-client

It's easy to build.  yarn install  yarn dev

Click the hamburger menu top left.  Click Donate, Click Sign in with Ledger nano,  Right click on something to Inspect element to see the console.

**Comment by lenondupe** [comment]
Doesn't seem to work. I get a blank window. Console logs an error:
Uncaught TypeError: Cannot read property 'length' of null
    at StellarAccounts.loadAccounts (webpack-internal:///./src/js/StellarAccounts.js:98)
    at new StellarAccounts (webpack-internal:///./src/js/StellarAccounts.js:10)
    at eval (webpack-internal:///./src/js/StellarAccounts.js:116)
    at Object../src/js/StellarAccounts.js (renderer.js:1365)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at eval (webpack-internal:///./src/js/StellarUtils.js:1)
    at Object../src/js/StellarUtils.js (renderer.js:1381)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules…ib/selector.js?type=script&index=0!./src/components/BalanceComponent.vue:1)
    at Object../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/BalanceComponent.vue (renderer.js:759)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at eval (webpack-internal:///./src/components/BalanceComponent.vue:1)
    at Object../src/components/BalanceComponent.vue (renderer.js:1309)

**Comment by lenondupe** [comment]
OK, got it to work. First apply the following patch:

```Index: src/components/DonateDialog.vue
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/components/DonateDialog.vue	(revision 387ef98308a2840290760f1ac18ff4ed55304fef)
+++ src/components/DonateDialog.vue	(revision )
@@ -74,15 +74,17 @@
         })
     },
     donate() {
-      new StellarLedger.Api(new StellarLedger.comm(Number.MAX_VALUE)).connect(
-        () => {
-          console.log('connected')
-          this.getPublicKey()
-        },
-        (err) => {
-          console.error(err)
-        }
-      )
+      StellarLedger.comm.create_async().then((comm) => {
+          new StellarLedger.Api(comm).getPublicKey_async("44'/148'/0'")
+            .then((result) => {
+              this.srcPublicKey = result['publicKey']
+              console.log(this.srcPublicKey)
+
+              this.status = 'Connected'
+              this.connected = true
+            })
+            }
+          )
     },
     getPublicKey() {
       StellarLedger.comm.create_async().then((comm) => {
Index: src/js/StellarAccounts.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/js/StellarAccounts.js	(revision 387ef98308a2840290760f1ac18ff4ed55304fef)
+++ src/js/StellarAccounts.js	(revision )
@@ -94,7 +94,7 @@
   loadAccounts() {
     const accounts = Helper.get('accounts')
 
-    if (accounts.length > 0) {
+    if (accounts && accounts.length > 0) {
       this._accounts = accounts
     } else {
       console.log('no accounts')
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- package.json	(revision 387ef98308a2840290760f1ac18ff4ed55304fef)
+++ package.json	(revision )
@@ -23,13 +23,14 @@
     "request-promise-native": "^1.0.5",
     "sillyname": "^0.1.0",
     "source-map-support": "^0.5.0",
-    "stellar-sdk": "^0.8.0",
-    "stellar-ledger-api": "2.0.0"
+    "stellar-ledger-api": "2.0.1",
+    "stellar-sdk": "^0.8.0"
   },
   "devDependencies": {
     "css-loader": "^0.28.8",
     "electron": "1.7.10",
     "electron-builder": "^19.52.1",
+    "electron-rebuild": "^1.7.3",
     "electron-webpack": "1.11.0",
     "electron-webpack-eslint": "^1.2.0",
     "electron-webpack-vue": "^1.1.0",
@@ -47,4 +48,4 @@
     "webpack": "^3.10.0",
     "webpack-build-notifier": "^0.1.21"
   }
-}
\ No newline at end of file
+}
```

The electron-rebuild allows you to rebuild native node modules against the version of nodeJs that your electron project is using. In your case this applies to the node_hid package.

In order to build node_hid however you need to have libssl-dev installed (OpenSSL headers).

```$ apt-get install libssl-dev```

No you can rebuild the native packages:

```$ ./node_modules/.bin/electron-rebuild```

Should now work.

**Comment by sgehrman** [comment]
Thanks, will take a look tomorrow. Sorry about that crash, I should test it on first launch

**Comment by sgehrman** [comment]
I'm getting this error:

Uncaught Error: Cannot find module 'ledgerco/src/ledger-comm-node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (f:\Github\stellar-client\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (f:\Github\stellar-client\node_modules\stellar-ledger-api\src\index.js:20:27)
    at Object.<anonymous> (f:\Github\stellar-client\node_modules\stellar-ledger-api\src\index.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by lenondupe** [comment]
Looks like Ledger have released a new library and the dependency version in my package.json uses a greater than version value so it will fetch the latest one which is no longer compatible. I'll fix it today.

**Comment by sgehrman** [comment]
It works now, thanks for the help!!

I do have one mystery though, it works if I add electron-rebuild and do the step to rebuild, but I've read that electron-builder does this automatically and that it's not recommended to use electron-rebuild with that.  I see it building node_hid, but it fails with a Uncaught Error: A dynamic link library (DLL) initialization routine failed. \\?\f:\Github\stellar-client\node_modules\node-hid\build\Release\HID.node

So, that's kind of annoying, but I'll research that and see what's up.

**Comment by sgehrman** [comment]
Sorry spoke too soon, the app launched without errors, but now I tried to connect ledger and got this:

OK, now got this:

f:\Github\stellar-client\node_modules\ledgerco\src\u2f-api.js:528 GET chrome-extension://kmendfapggjehodndflmmgagdbamhnfd/u2f-comms.html net::ERR_NOT_IMPLEMENTED

f:\Github\stellar-client\node_modules\ledgerco\src\u2f-api.js:544 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').
﻿

​

**Comment by lenondupe** [comment]
Did you apply the patch I provided in full? You need to use comm_node
instead of comm.

Op 20 jan. 2018 11:54 a.m. schreef "Steve Gehrman" <notifications@github.com

**Comment by sgehrman** [comment]
oh, sorry I did add the entire patch, but it must have been reverted as I have been switching branches and testing other stuff.  will try now.

**Comment by sgehrman** [comment]
OK, updated that, and now it doesn't seem to complete:

    StellarLedger.comm_node.create_async().then((comm) => {
        console.log(comm)
        new StellarLedger.Api(comm).getPublicKey_async("44'/148'/0'")
          .then((result) => {
            console.log('got here')

I never get to 'got here'

**Comment by lenondupe** [comment]
Is browser support disabled? Browser support must be disabled over node hid.

Op 20 jan. 2018 12:21 p.m. schreef "Steve Gehrman" <notifications@github.com

**Comment by sgehrman** [comment]
oh, right you did mention that previously.

OK, works now. I had turned on browser support as I was using Account Viewer.

Thanks!!  Seems to work.
