### ISSUE TITLE
Trouble with timeout for connect in Electron app

### ISSUE THREAD

**Issue by sgehrman** [lenondupe/stellar-ledger-api#7]
getting Invalid status 27904 passing a timeout value or no value if stellar nano app isn't running.

if i use timeout = Number.MAX_VALUE or Number.MAX_SAFE_INTEGER just fail instantly with 'Error: timeout'

I'm trying to get the behavior similar to stellar.org account viewer, button is dimmed until you connect and launch nano stellar app.  I assume the timeout is for this right?  

const timeout = 100000  

  StellarLedger.comm_node.create_async(timeout)
        .then((comm) => {
          new StellarLedger.Api(comm).connect(() => {
            this.connected = true
          }, (error) => {
            this.status = 'Error: ' + error
          })
        })

My code works if the stellar app is launched and ready to connect.

I tried to look at the code of ledgerco, but could not figure it out.  node and u2f are different, so maybe there is some bug?

Here's my code if you want to see it https://github.com/StellarKit/stellar-client

**Comment by lenondupe** [comment]
Yes timeout behaviour is different for the two protocols. IIRC for node if you don't specify a timeout at all it defaults to 0 which will give you the behaviour you are looking for.

**Comment by sgehrman** [comment]
I tried many variations, I could not get it working.  I tried not passing a parameter for timeout, but it just failed immediately if the nano wasn't ready to connect. I'm not sure If I tried passing in 0 for timeout, but not sure if that would work.

**Comment by sgehrman** [comment]
Same code on my website (using .comm) works great.  I just want to get it working in Electron. I'll take another look at it, but download my code and try for yourself if you have time. You probably could figure it out faster than me.  Thanks.

**Comment by sgehrman** [comment]
I've looked at ledgerco again, I think the timeout might not be the issue. 

I'm getting 27904 result immediately for either 0, or any value of timeout.

If nano is running and app is running it works, otherwise it doesn't

27904 
#define SW_INS_NOT_SUPPORTED                0x6d00

What does that error mean?

Thanks

**Comment by lenondupe** [comment]
If it fails to wait when the device is not connected you probably need to implement a simple monitor loop yourself.

```while (true) {
  try {
    setTimout(connect, 100);
    return;
  } catch (e) {
  }
}```

SW_INS_NOT_SUPPORTED means the client is trying to make a call to an app operation that does not exist. How are you getting this error? Which app version and which js api version are you using?

**Comment by sgehrman** [comment]
1.1.1 of the ledger app and     "stellar-ledger-api": "^2.0.4",

It happens every time for me if the ledger is plugged in, but the stellar ledger app isn't running.

**Comment by lenondupe** [comment]
Ah yes, that makes sense because the operation the api is calling is not available on the dashboard but only when the Stellar app is open. I would recommend to implement a simple connection monitor as described above.

**Comment by sgehrman** [comment]
OK, got it working.  I'll report the bug to ledgerhq

Here's my solution if anyone in the future needs it.

```
  connectLedgerNode() {
       const doConnect = () => {
        try {
        return StellarLedger.comm_node.create_async()
            .then((comm) => {
              new StellarLedger.Api(comm).connect(() => {
                this.connected = true
              }, (error) => {
                console.log(JSON.stringify(error))
              })
            })
        } catch (error) {
          console.log(JSON.stringify(error))
        }

        if (!this.connected) {
          setTimeout(doConnect, 1000)
        }
      }

      doConnect()
    }
```

**Comment by lenondupe** [comment]
I'm not very knowledgeable in javascript, but I think you need to use 'await' here. You're creating an asynchronous promise with create_async() that will handle the operation on a different thread while the method itself returns immediately. So good chance `this.connected` is not yet set when it is tested for subsequently.

**Comment by sgehrman** [comment]
Thanks for the tip.  I'll update it with await.  I haven't done much async js.
